# -*- coding: utf-8 -*-
"""agenteivan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYqC0oetbdfwNgBTPLVmMVajlAN4rYrc
"""

!pip install -q langchain_google_genai
!pip install -U langchain-community

import getpass
import os
import google.generativeai as genai

if 'GOOGLE_API_KEY' not in os.environ:
    os.environ['GOOGLE_API_KEY'] = getpass.getpass('Provide your Google API Key: ')

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain.tools import BaseTool, tool
from langchain_core.tools import StructuredTool

from langchain_google_genai import ChatGoogleGenerativeAI

# Configura tu LLM de Google Gemini
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",  # modelo de texto
    temperature=0.7
)

# Función que genera el cuestionario
def generar_cuestionario(tema: str, num_preguntas: int = 5) -> str:
    prompt = f"""
    Genera un cuestionario sobre el tema: {tema}.
    Incluye {num_preguntas} preguntas claras.
    Devuélvelas en formato lista.
    """
    response = llm.invoke(prompt)
    return response

tema = "Sistema Solar"
cuestionario = generar_cuestionario(tema, num_preguntas=5)
print(cuestionario)